descriptionFormat: ''
handle: plakate
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: true
name: Plakate
productFieldLayouts:
  28027a9a-e68b-4008-81d7-38004a5120b8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 062de57b-312a-4da1-a86a-73871e6c927c # SEO Shop Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: ddc1a314-5b75-48dd-8397-738ddb51f3c8 # SEO Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: a826a24c-c56d-41be-b131-258c043900a4 # Produkt Typ
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 2206365c-5bc6-412b-9b7b-652c26622090 # Listing Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f7d5d311-8bd1-4a2f-a8e5-642d9982779c # Enable Column ?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6082ab94-81c7-43df-936c-ca4af64122df # Product Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 79d148d3-2db8-4744-ba65-1430fd75626f # Product Gallery
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4c43e277-578d-470f-8572-70b3c0ec2212 # Grid Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 1c477e79-fe86-45aa-adb4-fe552e08d726 # Grid Height
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 507d8153-3d6d-4319-8c40-a9506fccd879 # Sticky?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f6811093-f45d-4453-ba1b-18e8ab567f50 # Show on Homepage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 6b970296-d52f-465f-9ff7-1efbcf2a12b2 # Theme Switch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 5bdde4af-80bb-4aa6-be5d-7b2d2cb62b7d # Hall of Fame
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Coordinator
        sortOrder: 2
      -
        elements:
          -
            fieldUid: d14a271e-c071-471c-85b6-215d9127e323 # Product SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
      -
        elements:
          -
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            warning: null
        name: Varianten
        sortOrder: 4
productTitleFormat: ''
siteSettings:
  bc63c03e-bdb9-4257-848b-bea06f5ce825: # Kaspar Allenbach
    hasUrls: true
    template: _entries/product
    uriFormat: 'shop/{slug}'
  cb7c4cc1-6fcf-4482-912c-87ce9bbe5d98: # Kaspar Allenbach en
    hasUrls: true
    template: _entries/product
    uriFormat: 'shop/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
variantFieldLayouts:
  19066cd4-84b8-48df-bd94-3fdeac36a3d8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            warning: null
            width: 75
          -
            fieldUid: 696ca585-692d-42e0-9b41-b5fa9f16e15a # GTIN
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 4518d03c-1046-4f3b-acd3-08531d0e5734 # Variant Thumb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 51134fad-f9e8-4897-b7dc-0687653933b4 # Produkt Gr√∂sse
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: a5ea6b41-33da-4e83-9937-751c16604ac2 # Produktionsart
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Inhalt
        sortOrder: 1
