columnSuffix: null
contentColumnType: text
fieldGroup: 03aa9c64-ff16-41f2-843d-7fe264ec168c # Checkout
handle: orderSuccessMessage
instructions: 'Erscheint in E-Mail, Order Page und PDF Quittung'
name: 'Order Success Message'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\redactor\Field
