field: 7117751f-a877-4277-b875-fafc34810791 # Grid Coordinator
fieldLayouts:
  8302f797-d225-413c-b7bf-5eb76d10837e:
    tabs:
      -
        elements:
          -
            fieldUid: d3b43846-e68e-4ecf-8ad0-94109e683a48 # Grid Width
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5eb4348e-c36c-48e5-a3a5-14bbcbe70363 # Grid Height
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5953ac4a-fb66-4c89-b92c-c1894300b26a # Grid Offset
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 95e4ec45-807e-419c-86a3-4f710f03a2e4 # Autoplay?
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 013938a5-20cd-44f2-ab2d-38b805db8698 # No Mobile
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5eb4348e-c36c-48e5-a3a5-14bbcbe70363: # Grid Height
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridHeight
    instructions: ''
    name: 'Grid Height'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Span 1'
            -
              - value
              - span1
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Span 2'
            -
              - value
              - span2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 3'
            -
              - value
              - span3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 4'
            -
              - value
              - span4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  95e4ec45-807e-419c-86a3-4f710f03a2e4: # Autoplay?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: autoplay
    instructions: ''
    name: 'Autoplay?'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  5953ac4a-fb66-4c89-b92c-c1894300b26a: # Grid Offset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridOffset
    instructions: ''
    name: 'Grid Offset'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Offset 0'
            -
              - value
              - offset0
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Offset 1'
            -
              - value
              - offset1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 2'
            -
              - value
              - offset2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 3'
            -
              - value
              - offset3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 4'
            -
              - value
              - offset4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 5'
            -
              - value
              - offset5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 6'
            -
              - value
              - offset6
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 7'
            -
              - value
              - offset7
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 8'
            -
              - value
              - offset8
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 9'
            -
              - value
              - offset9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 10'
            -
              - value
              - offset10
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 11'
            -
              - value
              - offset11
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 12'
            -
              - value
              - offset12
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  013938a5-20cd-44f2-ab2d-38b805db8698: # No Mobile
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: hideOnMobile
    instructions: ''
    name: 'No Mobile'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  d3b43846-e68e-4ecf-8ad0-94109e683a48: # Grid Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridWidth
    instructions: ''
    name: 'Grid Width'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Span 1'
            -
              - value
              - span1
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Span 2'
            -
              - value
              - span2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 3'
            -
              - value
              - span3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 4'
            -
              - value
              - span4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 5'
            -
              - value
              - span5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 6'
            -
              - value
              - span6
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 7'
            -
              - value
              - span7
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 8'
            -
              - value
              - span8
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 9'
            -
              - value
              - span9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 10'
            -
              - value
              - span10
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 11'
            -
              - value
              - span11
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 12'
            -
              - value
              - span12
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
